var PythonShell = require('python-shell');

var tweet1 = JSON.stringify({"created_at":"Thu Aug 13 02:26:29 +0000 2015","id":631653017843011584,"id_str":"631653017843011584","text":"LIVE on #Periscope https://t.co/LdTIuO4E7A","source":"<a href=\"https://periscope.tv\" rel=\"nofollow\">Periscope.TV</a>","truncated":false,"in_reply_to_status_id":null,"in_reply_to_status_id_str":null,"in_reply_to_user_id":null,"in_reply_to_user_id_str":null,"in_reply_to_screen_name":null,"user":{"id":17459292,"id_str":"17459292","name":"JohnChinello","screen_name":"JohnChinello","location":"San Diego, CA","description":"Travel addict and aspiring photgrapher and by day, Manager of Sales Training for Cars com in San Diego, CA","url":"http://t.co/pqTgwZtxbh","entities":{"url":{"urls":[{"url":"http://t.co/pqTgwZtxbh","expanded_url":"http://about.me/johnchinello","display_url":"about.me/johnchinello","indices":[0,22]}]},"description":{"urls":[]}},"protected":false,"followers_count":1308,"friends_count":1895,"listed_count":53,"created_at":"Tue Nov 18 05:08:40 +0000 2008","favourites_count":13,"utc_offset":-21600,"time_zone":"Mountain Time (US & Canada)","geo_enabled":true,"verified":false,"statuses_count":1087,"lang":"en","contributors_enabled":false,"is_translator":false,"is_translation_enabled":false,"profile_background_color":"022330","profile_background_image_url":"http://pbs.twimg.com/profile_background_images/83215424/JohnBike.jpg","profile_background_image_url_https":"https://pbs.twimg.com/profile_background_images/83215424/JohnBike.jpg","profile_background_tile":false,"profile_image_url":"http://pbs.twimg.com/profile_images/1264305330/ProfilePic2_normal.jpg","profile_image_url_https":"https://pbs.twimg.com/profile_images/1264305330/ProfilePic2_normal.jpg","profile_link_color":"0084B4","profile_sidebar_border_color":"A8C7F7","profile_sidebar_fill_color":"C0DFEC","profile_text_color":"333333","profile_use_background_image":true,"has_extended_profile":false,"default_profile":false,"default_profile_image":false,"following":false,"follow_request_sent":false,"notifications":false},"geo":null,"coordinates":null,"place":null,"contributors":null,"is_quote_status":false,"retweet_count":0,"favorite_count":0,"entities":{"hashtags":[{"text":"Periscope","indices":[8,18]}],"symbols":[],"user_mentions":[],"urls":[{"url":"https://t.co/LdTIuO4E7A","expanded_url":"https://www.periscope.tv/w/aJv31Tg2NTA3Mzd8NjAwMzY5MDmCQOhAibYXdoVRz1NldW0y2W4K0YZCFlhBtc1ORNyt_g==","display_url":"periscope.tv/w/aJv31Tg2NTA3…","indices":[19,42]}]},"favorited":false,"retweeted":false,"possibly_sensitive":false,"lang":"en"});
var tweet2 = JSON.stringify({"created_at":"Sun Jul 29 02:12:32 +0000 2012","id":229398975701188608,"id_str":"229398975701188608","text":"Enjoying a gorgeous desert evening! (@ Moab Utah) [pic]: http://t.co/YspxCvd9","source":"<a href=\"http://foursquare.com\" rel=\"nofollow\">Foursquare</a>","truncated":false,"in_reply_to_status_id":null,"in_reply_to_status_id_str":null,"in_reply_to_user_id":null,"in_reply_to_user_id_str":null,"in_reply_to_screen_name":null,"user":{"id":17459292,"id_str":"17459292","name":"JohnChinello","screen_name":"JohnChinello","location":"San Diego, CA","description":"Travel addict and aspiring photgrapher and by day, Manager of Sales Training for Cars com in San Diego, CA","url":"http://t.co/pqTgwZtxbh","entities":{"url":{"urls":[{"url":"http://t.co/pqTgwZtxbh","expanded_url":"http://about.me/johnchinello","display_url":"about.me/johnchinello","indices":[0,22]}]},"description":{"urls":[]}},"protected":false,"followers_count":1308,"friends_count":1895,"listed_count":53,"created_at":"Tue Nov 18 05:08:40 +0000 2008","favourites_count":13,"utc_offset":-21600,"time_zone":"Mountain Time (US & Canada)","geo_enabled":true,"verified":false,"statuses_count":1087,"lang":"en","contributors_enabled":false,"is_translator":false,"is_translation_enabled":false,"profile_background_color":"022330","profile_background_image_url":"http://pbs.twimg.com/profile_background_images/83215424/JohnBike.jpg","profile_background_image_url_https":"https://pbs.twimg.com/profile_background_images/83215424/JohnBike.jpg","profile_background_tile":false,"profile_image_url":"http://pbs.twimg.com/profile_images/1264305330/ProfilePic2_normal.jpg","profile_image_url_https":"https://pbs.twimg.com/profile_images/1264305330/ProfilePic2_normal.jpg","profile_link_color":"0084B4","profile_sidebar_border_color":"A8C7F7","profile_sidebar_fill_color":"C0DFEC","profile_text_color":"333333","profile_use_background_image":true,"has_extended_profile":false,"default_profile":false,"default_profile_image":false,"following":false,"follow_request_sent":false,"notifications":false},"geo":{"type":"Point","coordinates":[38.57047087,-109.55069851]},"coordinates":{"type":"Point","coordinates":[-109.55069851,38.57047087]},"place":{"id":"336d05d7fc7b160c","url":"https://api.twitter.com/1.1/geo/id/336d05d7fc7b160c.json","place_type":"city","name":"Moab","full_name":"Moab, UT","country_code":"US","country":"United States","contained_within":[],"bounding_box":{"type":"Polygon","coordinates":[[[-109.570595,38.556371],[-109.5228906,38.556371],[-109.5228906,38.588968],[-109.570595,38.588968]]]},"attributes":{}},"contributors":null,"is_quote_status":false,"retweet_count":0,"favorite_count":0,"entities":{"hashtags":[],"symbols":[],"user_mentions":[],"urls":[{"url":"http://t.co/YspxCvd9","expanded_url":"http://4sq.com/LVDrrl","display_url":"4sq.com/LVDrrl","indices":[57,77]}]},"favorited":false,"retweeted":false,"possibly_sensitive":false,"lang":"en"});

var options = {
  args: [tweet1, tweet2]
};

console.log(options.args);

PythonShell.run('python/classifyTweets.py', options, function (err, result) {
  if (err) throw err;
  console.log(result)
  // for(var i=0; i<result.length; i++){
  // 	console.log("Tweet ",i,":",result[i]);
  // }
});